import React from 'react';

export default function DataComponent() {
  return (
    <>
        <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
                <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
                <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
                <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
                <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
                <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
                <div>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                <p>0</p>
                <p>1</p>
                </div>
    </>
  )
}
